# 1.Numpy #

## 1.1矩阵、向量运算 ##

numpy相比传统的math库，提供更方便、更高效的向量、矩阵运算

### numpy能对向量的元素做统一处理 ###

**以sigmoid函数为例：**  
<font size = 4>
$sigmoid(x) = \frac{1}{1+e^{-x}}$
</font>  

分别用math库与numpy库进行实现

In [1]:
import math

def sigmoid(x):
    result = 1 / (1 + math.exp(-x))
    return result

In [2]:
x1 = 5
x2 = [3, 5, 7]

In [3]:
sigmoid(x1)

0.9933071490757153

In [4]:
sigmoid(x2)

TypeError: bad operand type for unary -: 'list'

可以看出math库对于向量的支持并不友好

In [9]:
import numpy as np

def sigmoid_np(x):
    result = 1 / (1 + np.exp(-x))
    return result

In [12]:
x1 = 5
x2 = np.array([3, 5, 7])

In [13]:
sigmoid_np(x1)

0.99330714907571527

In [14]:
sigmoid_np(x2)

array([ 0.95257413,  0.99330715,  0.99908895])

### 数据的归一化 #

数据归一化将数据缩放到[0,1]区间  
<br><br>
<font color='blue'>
**使用数据归一化有两点好处：**  
- 加速模型收敛  
- 抑制不同特征间的量级差距带来的权值偏重  
</font>  
最简单的归一化方法：对每行数据计算 <font size = 5>$\frac{x}{\| x\|}$  </font>

通过 np.linalg.norm(x, axis = 1, keepdims = True) 可以计算每行的 ${\| x\|}$

In [24]:
def nomalization(x):
    x_norm = np.linalg.norm(x, axis = 1, keepdims = True)
    print("norm = ",x_norm)
    result = x / x_norm
    return result

In [23]:
x = np.array([[1, 2], [3, 4]])

In [25]:
nomalization(x)

norm =  [[ 2.23606798]
 [ 5.        ]]


array([[ 0.4472136 ,  0.89442719],
       [ 0.6       ,  0.8       ]])

### 向量化 #

传统计算内积需要嵌套多层循环,而利用numpy库进行向量运算可以去除显示循环，大大提高效率  

**例如：**  
np.dot(matrix1, matrix2) 能实现矩阵乘法  
np.multiply(matrix1, matrix2) 能实现矩阵对应点相乘

In [26]:
matrix1 = [[1, 2], [3, 4]]
matrix2 = [[1, 2], [3, 4]]

In [63]:
import time

tic = time.time()
for i in range(np.shape(matrix1)[0]):
    for j in range(np.shape(matrix1)[1]):
        result[i][j] = matrix1[i][j] * matrix2[i][j]
toc = time.time()
print("result = \n", result)
print("time_comsume = ", str(1000 * (toc - tic)))

result = 
 [[ 1  4]
 [ 9 16]]
time_comsume =  0.5011558532714844


In [62]:
tic = time.time()
result = np.multiply(matrix1, matrix2)
toc = time.time()
print("result = \n", result)
print("time_comsume = ", str(1000 * (toc - tic)))

result = 
 [[ 1  4]
 [ 9 16]]
time_comsume =  0.4744529724121094


### 矩阵变换 #

np.reshape可用于对矩阵的维度进行变换  
**假设：**  
变换前的矩阵：mat.shape = (a, b)  
变换后的矩阵: mat.shape = (c, d)  
必须满足：a\*b = c\*d  

**注意：**  
将矩阵变为向量时,应指定目标形状为(x, 1)或(1, x)而不是(1) 

In [66]:
matrix = np.array([[1, 2], [3, 4]])
matrix = matrix.reshape(matrix.shape[0] * matrix.shape[1], 1)
matrix

array([[1],
       [2],
       [3],
       [4]])

## 1.2广播 ##

当(m, n)的矩阵与(m, 1)或(1, n)的向量进行{+  -  *  /}等运算时,会先将向量按列/行复制为(m, n)的矩阵，再进行两个矩阵对应点的两两运算

In [67]:
matrix = np.array([[1, 2], [3, 4]])
vec = np.array([1, 2])
matrix + vec

array([[2, 4],
       [4, 6]])